version: '3.8'
services:
  backend:
    build: ./m151-backend
    container_name: m151-backend
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./m151-frontend
    container_name: m151-frontend
    ports:
      - 8080:80
    expose:
      - 80

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - m151-postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - m151-redis:/var/lib/postgresql/data

volumes:
  m151-postgres:
  m151-redis:


